config/routes.rb
Rails.application.routes.draw do
  resources :personnels
  root to: 'home#index'
  resources :appointments
  resources :diseases
  resources :departments
  resources :records
  resources :nurses
  resources :doctors
  resources :pharmacists
  devise_for :users
  resources :frontdesk
  resources :home, only: [:index] do 
    collection do
      get :admin #, :personnels,:download_data, :new_personnel 
    end

    # member do
    #   get :show_personnel, :edit_personnel
    #   post :update_personnel
    # end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :uuid             not null, primary key
#  admin_name             :string
#  admin_update_time      :datetime
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :inet
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  first_name             :string
#  is_verified            :boolean          default(FALSE)
#  last_name              :string
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :inet
#  phone_number           :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  sign_in_count          :integer          default(0), not null
#  title                  :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :user_roles
  has_many :roles, through: :user_roles

  def fullname
    self.first_name + " " + self.last_name
  end

  def is_superadmin?
  	is_type?("superadmin")
  end

  def is_admin?
  	is_type?("admin")  	
  end

  def is_frontdesk?
    is_type?("frontdesk")
  end  

  def is_nurse?
    is_type?("nurse")
  end  

  def is_doctor?
    is_type?("doctor")
  end  

  def is_pharmacist?
  	is_type?("pharmacist")
  end

   def self.to_csv
    attributes = %w{id email first_name last_name}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |user|
        csv << attributes.map{ |attr| user.send(attr) }
      end
    end
  end

  # def self.to_csv
  #   CSV.generate do |csv|
  #     csv << column_names
  #     all.each do |result|
  #       csv << result.attributes.values_at(*column_names)
  #     end
  #   end
  # end


  # def self.new_with_session(params, session)
  #   super.tap do |user|
  #     if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
  #       user.email = data["email"] if user.email.blank?
  #     end
  #   end
  # end

  # def self.from_omniauth(auth)
  #   where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  #     user.email = auth.info.email
  #     user.password = Devise.friendly_token[0,20]
  #     user.name = auth.info.name   # assuming the user model has a name
  #     user.image = auth.info.image # assuming the user model has an image
  #   end
  # end

  private
	def is_type? type
		self.roles.map(&:name).include?(type) ? true : false
	end
end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
     super
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
  <div class="row">
  <div class="col-md-4 offset-md-4">
  <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <div class="form-group">
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true, autocomplete: "email", :class => "form-control", :placeholder=> "Enter Email" %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off", :class=>"form-control", :placeholder=>"Password" %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off", :class=>"form-control", :placeholder=>"Confirm Password" %>
  </div>

  <div class="form-group">
    <%= f.submit "Sign up", :class=>"btn btn-primary"%>
  </div>

  <%= render "devise/shared/links" %>

  <% end %>
  </div>
  <div class="col-md-4">
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
      <!-- start banner Area -->
      <section class="banner-area relative about-banner" id="home"> 
        <div class="overlay overlay-bg"></div>
        <div class="container">       
          <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content col-lg-12">
              <h1 class="text-white">
                Front Desk        
              </h1> 
              <p class="text-white link-nav"><a href="index.html">Home </a>  <span class="fa fa-arrow-right"></span>  <a href="contact.html"> Records</a></p>
            </div>  
          </div>
        </div>
      </section>
      <!-- End banner Area -->  


<% count = 0 %>

<% if @users.count > 0 %>
  <div class="limiter table-responsive">
    <div class="container-table100">
      <div class="wrap-table100">
        <p id="notice"><%= notice %></p>
        <%= link_to 'New Personnel', new_user_path %>
        <div class="table100">
            <table>
              <thead>
                <tr>
                  <th>S/No</th>
                  <th>First Name</th>
                  <th>Last Name</th>
                  <th>Title</th>
                  <th>Phone Number</th>
                  <th>Email</th>
                  <th>Added By</th>
                  <th colspan="3"></th>
                </tr>
              </thead>

              <tbody>
                <% @users.each do |user| %>
                  <% count += 1 %>
                  <tr>
                    <td><%= count %></td>
                    <td><%= user.first_name %></td>
                    <td><%= user.last_name %></td>
                    <td><%= user.title %></td>
                    <td><%= user.phone_number %></td>
                    <td><%= user.email %></td>
                    <td><%= user.admin_name %></td>
                    <td><%= link_to 'Show', user %></td>
                    <td><%= link_to 'Edit', edit_user_path(user) %></td>
                    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
        </div>
        <%= link_to 'New Personnel', new_user_path %>
      </div>
    </div>
  </div>

<br>
<% else %>
   <!-- Start facilities Area -->
      <section class="facilities-area section-gap">
        <div class="container">
                <div class="row d-flex justify-content-center">
                    <div class="menu-content pb-70 col-lg-7">
                        <div class="title text-center">
                          <p id="notice"><%= notice %></p>
                            <h1 class="mb-10">No Personnels.</h1>
                            <p>No personnel record has been inputted. Click on <%= link_to 'New Personnel', new_user_path %> to start.</p>
                        </div>
                    </div>
                </div>
        </div>  
      </section>
      <!-- End facilities Area -->
<% end %>

app/views/users/new.html.erb
      <!-- start banner Area -->
      <section class="banner-area relative about-banner" id="home"> 
        <div class="overlay overlay-bg"></div>
        <div class="container">       
          <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content col-lg-12">
              <h1 class="text-white">
                Administrator        
              </h1> 
              <p class="text-white link-nav"><a href="index.html">Home </a>  <span class="lnr lnr-arrow-right"></span>  <a href="contact.html"> Add Personnel</a></p>
            </div>  
          </div>
        </div>
      </section>
      <!-- End banner Area -->  

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>