config/routes.rb
Rails.application.routes.draw do
  resources :personnels
  root to: 'home#index'
  resources :appointments
  resources :diseases
  resources :departments
  resources :records
  resources :nurses
  resources :doctors
  resources :pharmacists
  devise_for :users
  resources :frontdesk
  resources :home, only: [:index] do 
    collection do
      get :admin #, :personnels,:download_data, :new_personnel 
    end

    # member do
    #   get :show_personnel, :edit_personnel
    #   post :update_personnel
    # end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_user, only: [:show_personnel, :edit_personnel]

  def index
  	@appointment = Appointment.new
  end


  def profile
  end

  def download_data
    @users = User.all

    respond_to do |format|
      format.html
      format.csv { send_data @users.to_csv, filename: "Medical_Records-#{Date.today}.csv" }
    end
  end

  # def personnels
  #   @users = User.all
  # end

  # def new_personnel
  #   @user = User.new
  # end

  # def create_personnel
  #   @user = User.new(user_params)

  #   respond_to do |format|
  #     if @user.save
  #       flash[:success] = "Hi #{@user.first_name} was successfully created."
  #       format.html { redirect_to root_path, success: 'Appointment was successfully created.' }
  #       format.json { render :show, status: :created, location: @user }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @appointment.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # def show_personnel
  #   set_user
  # end

  # def edit_personnel
  #   set_user
  # end

  # def update_personnel
  #   set_user
  # end

  def admin

    @state = ""
    if params[:term].nil?
      @records = Record.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)
      @state = "default"
      report(@records)
    else
      case params[:term]
      when "week"
        @records = Record.where(created_at: DateTime.now.beginning_of_week..DateTime.now.end_of_week)
        @state = "week"
        report(@records)
      when "month"
        @state = "month"
        @records = Record.where(created_at: DateTime.now.beginning_of_month..DateTime.now.end_of_month)
        report(@records)
      when "year"
        @state = "year"
        @records = Record.where(created_at: DateTime.now.beginning_of_year..DateTime.now.end_of_year)
        report(@records)
      when "all"
        @state = "all"
        @records = Record.all
        report(@records)
      else
        @state = "selected_date"
        @records = Record.where(created_at: Date.parse(params[:term]).beginning_of_day..Date.parse(params[:term]).end_of_day)
        report(@records)
      end
    end

    # if params[:term]
    #   @records = Record.where(created_at: Date.parse(params[:term]).beginning_of_day..Date.parse(params[:term]).end_of_day)
    # elsif params[:week]
    #   @records = Record.where(created_at: DateTime.now.beginning_of_week..DateTime.now.end_of_week)
    # elsif params[:month]
    #   @records = Record.where(created_at: DateTime.now.beginning_of_month..DateTime.now.end_of_month)
    # elsif params[:year]
    #   @records = Record.where(created_at: DateTime.now.beginning_of_year..DateTime.now.end_of_year)
    # elsif params[:all]
    #   @records = Record.all
    # else
    #   @records = Record.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)
    # end
  end

  private

  def set_user
      @user = User.find(params[:id])
    end

  def report(records)
      respond_to do |format|
      format.html
      format.csv { send_data records.to_csv, filename: "Medical_Records-#{Date.today}.csv" }
    end
  end

  def user_params
      params.require(:user).permit(:first_name, :last_name, :phone_number, :title)
    end

end

app/views/home/admin.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
<!-- start banner Area -->
			<section class="banner-area relative about-banner" id="home">	
				<div class="overlay overlay-bg"></div>
				<div class="container">				
					<div class="row d-flex align-items-center justify-content-center">
						<div class="about-content col-lg-12">
							<h1 class="text-white">
								Admin		
							</h1>
								<div class="row">
									<div class="col-md-4">
										<!-- <a href="#" class="genric-btn primary radius">Primary</a> -->
									</div>
									<div class="col-md-4">
										<div class="search">
							              <%= form_tag admin_home_index_path, method: :get do %>
							                <%= date_field_tag :term, Date.today,  :placeholder => "Select a date" , :class=>"input" %>
							                <%= button_tag(type: 'submit',name:nil, class: "search-btn") do %>
							                 <i class="fa fa-search"></i>
							                <% end %>
							              <% end %>
							            </div>
									</div>
									<div class="col-md-4">									
									</div>
								</div>
						</div>	
					</div>
				</div>
			</section>
<!-- End banner Area -->	

			<!-- Start Align Area -->
			<div class="whole-wrap">
				<div class="container">
					<div class="section-top-border">
						<div class="row text-center">
							<div class="button-group-area mt-40">
								<%= link_to "Medical personnel", personnels_path , :class => "genric-btn primary radius" %>
                                <%= link_to "Appointments", appointments_path , :class => "genric-btn info radius" %>
                                <%= link_to "This Week", admin_home_index_path(:term => "week"), :class => "genric-btn danger radius" %>
                                <%= link_to "This Month", admin_home_index_path(:term => "month") , :class => "genric-btn success radius" %>
                                <%= link_to "This Year", admin_home_index_path(:term => "year") , :class => "genric-btn purple radius" %>
                                <%= link_to "All Records", admin_home_index_path(:term => "all") , :class => "genric-btn warning radius" %>
							</div>
						</div>
					</div>
			
					<!-- <div class="section-top-border">
						<h3 class="mb-30">Analytics</h3>
						<div class="row">
							<div class="col-md-6">
								<canvas id="patientsChart" width="400" height="400"></canvas>
							</div>
							<div class="col-md-6">
								<div class="single-defination">
									<canvas id="personnelChart" width="400" height="400"></canvas>
								</div>
							</div>
						</div>
					</div>	 -->				
				</div>
			</div>
			<!-- End Align Area -->

<% count = 0 %>

<% if @records.count > 0 %>
  
  <div class="limiter">
    <div class="container-table100">
      <div class="wrap-table100">
        <p id="notice"><%= notice %></p>
        <div class="table100">
          <table class="table-responsive">
            <thead>
              <tr>
                <th>S/No</th>
                <th>Date</th>
                <th>Name</th>
                <th>Age</th>
                <th>Gender</th>
                <th>Department</th>
                <th>Complaints</th>
                <th>Diagnosis</th>
                <th>Treatment</th>
                <th>Height</th>
                <th>Weight</th>
                <th>Temperature</th>
                <th>Blood pressure</th>
                <th>Drugs given</th>
                <th colspan="1"></th>
              </tr>
            </thead>

            <tbody>
              <% @records.each do |record| %>
              <% count+=1 %>
                <tr>
                  <td><%= count %></td>
                  <td><%= record.created_at.to_date %></td>
                  <td><%= record.name %></td>
                  <td><%= record.age %></td>
                  <td><%= record.gender %></td>
                  <td><%= record.department.name %></td>
                  <td><%= record.complaints %></td>
                  <td><%= record.diagnosis %></td>
                  <td><%= record.treatment %></td>
                  <td><%= record.height %></td>
                  <td><%= record.weight %></td>
                  <td><%= record.temperature %></td>
                  <td><%= record.blood_pressure %></td>
                  <td><%= record.drugs_given %></td>
                  <td><%= link_to 'Show', record %></td> 
                  <!-- <td><%= link_to 'Edit', edit_record_path(record) %></td> -->
                  <!-- <td><%= link_to 'Destroy', record, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
                </tr>
              <% end %>
            </tbody>
          </table>

          </div>
        </br>
        <%= link_to 'New Record', new_record_path %>
      
        
        <%= link_to "Generate Report", admin_home_index_path(format: "csv") , :class => "genric-btn info radius" %>
      </div>
    </div>
  </div>

<br>
<% else %>
   <!-- Start facilities Area -->
      <section class="facilities-area section-gap">
        <div class="container">
                <div class="row d-flex justify-content-center">
                    <div class="menu-content pb-70 col-lg-7">
                        <div class="title text-center">
                            <h1 class="mb-10">No Records.</h1>
                            <p>No patient record has been inputted for today. Click on <%= link_to 'New Record', new_frontdesk_path %> to start.</p>
                        </div>
                    </div>
                </div>
        </div>  
      </section>
      <!-- End facilities Area -->
<% end %>

<script>
var ctx = document.getElementById("patientsChart").getContext('2d');
var patientsChart = new Chart(ctx, {
    type: 'line',
    data: {
        labels: ["Red", "Blue", "Yellow", "Green", "Purple", "Orange"],
        datasets: [{
            label: '# of Patients',
            data: [12, 19, 3, 5, 2, 3],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});

var ctx = document.getElementById("personnelChart").getContext('2d');
var personnelChart = new Chart(ctx, {
    type: 'line',
    data: {
        labels: ["Red", "Blue", "Yellow", "Green", "Purple", "Orange"],
        datasets: [{
            label: '# of Medical Personnels',
            data: [12, 19, 3, 5, 2, 3],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
</script>

app/views/home/new_personnel.html.erb
<div class="row top-margin headline">
  <div class="col-md-12 text-center">
    <h2>Sign up</h2>
  </div> 
</div>


<div class="row">
  <div class="col-md-4 offset-md-4">
  <%= form_tag(@user) do |f| %>

  <div class="form-group">
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true, autocomplete: "email", :class => "form-control", :placeholder=> "Enter Email" %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off", :class=>"form-control", :placeholder=>"Password" %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off", :class=>"form-control", :placeholder=>"Confirm Password" %>
  </div>

  <div class="form-group">
    <%= f.submit "Add User", :class=>"btn btn-primary"%>
  </div>

  <%= render "devise/shared/links" %>

  <% end %>
  </div>
  <div class="col-md-4">
  </div>
</div>

app/views/home/personnels.html.erb
      <!-- start banner Area -->
      <section class="banner-area relative about-banner" id="home"> 
        <div class="overlay overlay-bg"></div>
        <div class="container">       
          <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content col-lg-12">
              <h1 class="text-white">
                All Personnel       
              </h1> 
              <p class="text-white link-nav"><a href="index.html">Home </a>  <span class="lnr lnr-arrow-right"></span>  Records</p>
            </div>  
          </div>
        </div>
      </section>
      <!-- End banner Area -->

<% count = 0 %>

<% if @users.count > 0 %>
  <div class="limiter">
    <div class="container-table100">
      <div class="wrap-table100">
        <p id="notice"><%= notice %></p>
        <%= link_to 'New Personnel', new_user_registration_path %>
        <div class="table100">
            <table>
              <thead>
                <tr>
                  <th>S/No</th>
                  <th>First Name</th>
                  <th>Last Name</th>
                  <th>Title</th>
                  <th>Phone Number</th>
                  <th>Email</th>
                  <th>Added By</th>
                  <th colspan="3"></th>
                </tr>
              </thead>

              <tbody>
                <% @users.each do |user| %>
                  <% count += 1 %>
                  <tr>
                    <td><%= count %></td>
                    <td><%= user.first_name %></td>
                    <td><%= user.last_name %></td>
                    <td><%= user.title %></td>
                    <td><%= user.phone_number %></td>
                    <td><%= user.email %></td>
                    <td><%= user.admin_name %></td>                    
                    <td><%= link_to 'Edit',  edit_user_registration_path(user) %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
        </div>
        <%= link_to 'New Personnel', new_user_registration_path %>
      </div>
    </div>
  </div>

<br>
<% else %>
   <!-- Start facilities Area -->
      <section class="facilities-area section-gap">
        <div class="container">
                <div class="row d-flex justify-content-center">
                    <div class="menu-content pb-70 col-lg-7">
                        <div class="title text-center">
                          <p id="notice"><%= notice %></p>
                            <h1 class="mb-10">No Personnels.</h1>
                            <p>No personnel record has been inputted. Click on <%= link_to 'New Personnel', new_user_registration_path %> to start.</p>
                        </div>
                    </div>
                </div>
        </div>  
      </section>
      <!-- End facilities Area -->
<% end %>