config/routes.rb
Rails.application.routes.draw do
  resources :personnels
  root to: 'home#index'
  resources :appointments
  resources :diseases
  resources :departments
  resources :records
  resources :nurses
  resources :doctors
  resources :pharmacists
  devise_for :users
  resources :frontdesk
  resources :home, only: [:index] do 
    collection do
      get :admin #, :personnels,:download_data, :new_personnel 
    end

    # member do
    #   get :show_personnel, :edit_personnel
    #   post :update_personnel
    # end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/record.rb
# == Schema Information
#
# Table name: records
#
#  id                     :uuid             not null, primary key
#  address                :string
#  admin_name             :string
#  admin_update_time      :datetime
#  blood_pressure         :string
#  complaints             :string
#  diagnosis              :string
#  dob                    :date
#  doctor_name            :string
#  doctor_update_time     :datetime
#  doctor_updated         :boolean          default(FALSE)
#  drugs_given            :string
#  front_desk_name        :string
#  gender                 :string
#  health_care_provider   :string
#  height                 :string
#  name                   :string
#  nurse_name             :string
#  nurse_update_time      :datetime
#  nurse_updated          :boolean          default(FALSE)
#  pharmacist_name        :string
#  pharmacist_update_time :datetime
#  pharmacist_updated     :boolean          default(FALSE)
#  temperature            :string
#  treatment              :string
#  weight                 :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  department_id          :uuid
#
# Indexes
#
#  index_records_on_department_id  (department_id)
#
# Foreign Keys
#
#  fk_rails_...  (department_id => departments.id)
#

class Record < ApplicationRecord
	belongs_to :department
	has_many :record_icds
	has_many :icds, through: :record_icds

	validates :dob, :presence => true

	def age
		age = ((Date.today - dob).to_i/365.25).to_i
		if age < 1
			(((Date.today - dob).to_i/30.4167).to_i).to_s + " month(s)"
		else
			age
		end
	end

	# def department
	# 	department.name
 #  	end

	def self.to_csv
    attributes = %w{name age gender address health_care_provider complaints diagnosis treatment height weight temperature blood_pressure 
    	drugs_given front_desk_name nurse_name doctor_name pharmacist_name created_at}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |user|
        csv << attributes.map{ |attr| user.send(attr) }
      end
    end
  end

  self.per_page = 10

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_record, only: [:show, :edit, :update, :destroy]

  # GET /records
  # GET /records.json
  def index
  #change query parameters for the where clause based on who has updated
    if current_user.is_frontdesk?
      @records = Record.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)
      render "/frontdesk/index"
    elsif current_user.is_nurse?
      @records = Record.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)
      render "/nurses/index"
    elsif current_user.is_doctor?
      @records = Record.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).where(nurse_updated: true)
      render "/doctors/index"
    elsif current_user.is_pharmacist?
      @records = Record.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).where(doctor_updated: true)
      render "/pharmacists/index"
    else
      @records = Record.all
    end
  end

  # GET /records/1
  # GET /records/1.json
  def show
    if current_user.is_frontdesk?
      redirect_to frontdesk_path(@record)
    elsif current_user.is_nurse?
      redirect_to nurse_path(@record)
    elsif current_user.is_doctor?
      redirect_to doctor_path(@record)
    elsif current_user.is_pharmacist?
      redirect_to pharmacist_path(@record)
    elsif current_user.is_admin?
    end
  end

  # GET /records/new
  def new
    @record = Record.new
    if current_user.is_frontdesk?
      redirect_to "/frontdesk/new"
    elsif current_user.is_nurse?
      render "/nurses/new"
    elsif current_user.is_doctor?
      render "/doctors/new"
    elsif current_user.is_pharmacist?
      render "/pharmacists/new"
    elsif current_user.is_admin?
    end
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)
    set_user_and_time

    respond_to do |format|
      if @record.save
            if current_user.is_frontdesk?
              format.html { redirect_to frontdesk_path(@record), notice: 'Record was successfully created.' }
            elsif current_user.is_nurse?
              format.html { redirect_to nurse_path(@record), notice: 'Record was successfully created.' }
            elsif current_user.is_doctor?
              format.html { redirect_to doctor_path(@record), notice: 'Record was successfully created.' }
            elsif current_user.is_pharmacist?
              format.html { redirect_to pharmacst_path(@record), notice: 'Record was successfully created.' }
            else
              format.html { redirect_to @record, notice: 'Record was successfully created.' }
            end
        # format.html { redirect_to @record, notice: 'Record was successfully created.' }
        # format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    set_user_and_time
    # @record.record_icds.delete_all
    # icd_string= params["icd_array"]
    # if icd_string.length > 1
    #   icd_string.split(",").each do |icd|
    #     @record.record_icds.create(icd_id: icd)
    #   end
    # end
    

    respond_to do |format|
      if @record.update(record_params)
        if current_user.is_frontdesk?
              format.html { redirect_to frontdesk_index_path, notice: 'Patient record was successfully created.' }
            elsif current_user.is_nurse?
              format.html { redirect_to nurse_path(@record), notice: 'Patient record was successfully updated.' }
            elsif current_user.is_doctor?
              format.html { redirect_to doctor_path(@record), notice: 'Patient record was successfully updated.' }
            elsif current_user.is_pharmacist?
              format.html { redirect_to pharmacist_path(@record), notice: 'Patient record was successfully updated.' }
            else
              format.html { redirect_to @record, notice: 'Patient record was successfully updated.' }
            end
        # format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        # format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:icd_id,:name, :dob, :gender, :address, :health_care_provider, :department_id, :complaints, :diagnosis, :treatment, :height, :weight, :temperature, :blood_pressure, :drugs_given, :front_desk_updated, :nurse_updated, :doctor_updated, :pharmarcist_updated, :front_desk_name, :nurse_name, :doctor_name, :pharmacist_name, :nurse_update_time, :doctor_update_time, :pharmacist_update_time)
    end

    def set_user_and_time
          if current_user.is_frontdesk?
            @record.front_desk_name = current_user.fullname
          elsif current_user.is_nurse?
            @record.nurse_update_time = DateTime.now
            @record.nurse_name = current_user.fullname
            @record.nurse_updated = true
          elsif current_user.is_doctor?
            @record.doctor_name = current_user.fullname
            @record.doctor_update_time = DateTime.now
            @record.doctor_updated = true
            puts params[:icd_id]
          elsif current_user.is_pharmacist?
            @record.pharmacist_name = current_user.fullname
            @record.pharmacist_update_time = DateTime.now
            @record.pharmacist_updated = true
          else
            @record.admin_name = current_user.fullname
            @record.admin_update_time = DateTime.now
          end
    end

end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.erb
<!-- Start contact-page Area -->
      <section class="contact-page-area section-gap">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <%= form_for(record) do |f| %>
                <% if record.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(record.errors.count, "error") %> prohibited this record from being saved:</h2>

                    <ul>
                    <% record.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %>

                <div class="col-lg-6 form-group">
                  <!-- <%= f.label :name %> -->
                  <%= f.text_field :name, class: "common-input mb-20 form-control", placeholder: "Fullname" %>
                </div>

                <div class="col-lg-6 form-group">
                  <!-- <%= f.label :years %> -->
                  <%= f.date_field :dob, class: "common-input mb-20 form-control", placeholder: "mm/dd/yyyy"%>
                </div>

                <div class="col-lg-6 form-group inline">
                  <!-- <%= f.label :gender %> -->  
                  <div class="row">
                    <div class="col-lg-2 visible-lg-inline">
                      <%= f.label :gender, "Male", :value => "Male"  %>
                      <%= f.radio_button :gender,'Male' %>
                    </div>
                    <div class="col-lg-2">
                      <%= f.label :gender, "Female", :value => "Female" %>
                    <%= f.radio_button :gender, 'Female', :checked => true %>
                    </div>
                  </div>                                   
                    
                </div>

                <div class="col-lg-6 form-group">
                  <!-- <%= f.label :address %> -->
                  <%= f.text_field :address, class: "common-input mb-20 form-control", placeholder: "Address"  %>
                </div>

                <div class="col-lg-6 form-group">
                  <!-- <%= f.label :health_care_provider %> -->
                  <%= f.text_field :health_care_provider , class: "common-input mb-20 form-control", placeholder: "Health care provider" %>
                </div>

                <div class="col-lg-6 form-group">
                  <!-- <%= f.label :department %> -->
                   <%= f.collection_select :department_id, Department.order(:name), :id, :name, {},{class: "common-input mb-20 form-control"} %>
                  
                </div> 

                <div class="col-lg-6 form-group">
                  <!-- <%= f.label :height %> -->
                  <%= f.text_field :height, class: "common-input mb-20 form-control", placeholder: "Height"  %>
                </div>

                <div class="col-lg-6 form-group">
                  <!-- <%= f.label :weight %> -->
                  <%= f.text_field :weight, class: "common-input mb-20 form-control", placeholder: "Weight"  %>
                </div>

                <div class="col-lg-6 form-group">
                  <!-- <%= f.label :temperature %> -->
                  <%= f.text_field :temperature, class: "common-input mb-20 form-control", placeholder: "Temperature"  %>
                </div>

                <div class="col-lg-6 form-group">
                  <!-- <%= f.label :blood_pressure %> -->
                  <%= f.text_field :blood_pressure, class: "common-input mb-20 form-control", placeholder: "Blood Pressure"  %>
                </div>

                <div class="col-lg-6 form-group">
                  <!-- <%= f.label :complaints %> -->
                  <%= f.text_area :complaints , class: "common-input mb-20 form-control", placeholder: "Complaints" %>
                </div>

                <div class="col-lg-6 form-group">
                  <!-- <%= f.label :diagnosis %> -->
                  <%= f.collection_select :icd_id, Icd.order(:title), :id, :title, {},{class: "common-input mb-20 form-control"} %>
                </div>

                <div class="col-lg-6 form-group">
                  <!-- <%= f.label :treatment %> -->
                  <%= f.text_area :treatment, class: "common-input mb-20 form-control", placeholder: "Treatment"  %>
                </div>

                <div class="col-lg-6 form-group">
                  <!-- <%= f.label :drugs_given %> -->
                  <%= f.text_field :drugs_given , class: "common-input mb-20 form-control", placeholder: "Drugs given" %>
                </div>

                <div class="actions">
                  <%= f.submit "SUBMIT", :class=>"genric-btn primary" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>  
      </section>
      <!-- End contact-page Area -->

app/views/records/edit.html.erb
      <!-- start banner Area -->
      <section class="banner-area relative about-banner" id="home"> 
        <div class="overlay overlay-bg"></div>
        <div class="container">       
          <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content col-lg-12">
              <h1 class="text-white">
                Update Patient Record        
              </h1> 
              <p class="text-white link-nav"><a href="index.html">Home </a>  <span class="fa fa-arrow-right"></span>  <a href="contact.html">Update Record</a></p>
            </div>  
          </div>
        </div>
      </section>
      <!-- End banner Area --> 

<%= render 'form', record: @record %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

app/views/records/index.html.erb
      <!-- start banner Area -->
      <section class="banner-area relative about-banner" id="home"> 
        <div class="overlay overlay-bg"></div>
        <div class="container">       
          <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content col-lg-12">
              <h1 class="text-white">
                Administrator        
              </h1> 
              <p class="text-white link-nav"><a href="index.html">Home </a>  <span class="lnr lnr-arrow-right"></span>  <a href="contact.html"> Records</a></p>
            </div>  
          </div>
        </div>
      </section>
      <!-- End banner Area -->  
<% count = 0 %>

<% if @records.count > 0 %>
  
  <div class="limiter table-responsive">
    <div class="container-table100">
      <div class="wrap-table100">
        <p id="notice"><%= notice %></p>
        <div class="table100">
          <table>
            <thead>
              <tr>
                <th>S/No</th>
                <th>Date</th>
                <th>Name</th>
                <th>Age</th>
                <th>Gender</th>
                <th>Department</th>
                <th>Complaints</th>
                <th>Diagnosis</th>
                <th>Treatment</th>
                <th>Height</th>
                <th>Weight</th>
                <th>Temperature</th>
                <th>Blood pressure</th>
                <th>Drugs given</th>
                <th colspan="1"></th>
              </tr>
            </thead>

            <tbody>
              <% @records.each do |record| %>
              <% count+=1 %>
                <tr>
                  <td><%= count %></td>
                  <td><%= record.created_at.to_date %></td>
                  <td><%= record.name %></td>
                  <td><%= record.age %></td>
                  <td><%= record.gender %></td>
                  <td><%= record.department.name %></td>
                  <td><%= record.complaints %></td>
                  <td><%= record.icd.title %></td>
                  <td><%= record.treatment %></td>
                  <td><%= record.height %></td>
                  <td><%= record.weight %></td>
                  <td><%= record.temperature %></td>
                  <td><%= record.blood_pressure %></td>
                  <td><%= record.drugs_given %></td>
                  <td><%= link_to 'Show', record %></td> 
                  <!-- <td><%= link_to 'Edit', edit_record_path(record) %></td> -->
                  <!-- <td><%= link_to 'Destroy', record, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
                </tr>
              <% end %>
            </tbody>
          </table>

          </div>
        </br>
        <%= link_to 'New Record', new_record_path %>
        <%= link_to "Download Records", personnels_home_index_path , :class => "genric-btn info radius" %>
      </div>
    </div>
  </div>

<br>
<% else %>
   <!-- Start facilities Area -->
      <section class="facilities-area section-gap">
        <div class="container">
                <div class="row d-flex justify-content-center">
                    <div class="menu-content pb-70 col-lg-7">
                        <div class="title text-center">
                            <h1 class="mb-10">No Records.</h1>
                            <p>No patient record has been inputted for today. Click on <%= link_to 'New Record', new_frontdesk_path %> to start.</p>
                        </div>
                    </div>
                </div>
        </div>  
      </section>
      <!-- End facilities Area -->
<% end %>

app/views/records/show.html.erb
<!-- Start contact-page Area -->
      <section class="contact-page-area section-gap">
        <div class="container">
          <div class="row"> 
              <div class="col-lg-12">
                 <p id="notice"><%= notice %></p>
              </div>         
            <div class="col-lg-4 d-flex flex-column address-wrap">
              <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-user"></span>
                </div>
                <div class="contact-details">
                  <h5>Name</h5>
                  <p>
                    <%= @record.name %>
                  </p>
                </div>
              </div>
              <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-mustache"></span>
                </div>
                <div class="contact-details">
                  <h5>Date Of Birth</h5>
                  <p><%= @record.dob %></p>
                </div>
              </div>
              <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-map-marker"></span>
                </div>
                <div class="contact-details">
                  <h5>Address</h5>
                  <p><%= @record.address %></p>
                </div>
              </div> 
              <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-apartment"></span>
                </div>
                <div class="contact-details">
                  <h5>Health Care Provider</h5>
                  <p><%= @record.health_care_provider %></p>
                </div>
              </div> 
              <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-license"></span>
                </div>
                <div class="contact-details">
                  <h5>Address</h5>
                  <p><%= @record.department.name %></p>
                </div>
              </div> 
              <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-user"></span>
                </div>
                <div class="contact-details">
                  <h5>Front Desk Personnel</h5>
                  <p><%= @record.front_desk_name %></p>
                </div>
              </div>  
            </div>

            <div class="col-lg-4 d-flex flex-column address-wrap"> 
            <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-pointer-down"></span>
                </div>
                <div class="contact-details">
                  <h5>Weight</h5>
                  <p><%= @record.weight %></p>
                </div>
              </div> 
              <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-pointer-up"></span>
                </div>
                <div class="contact-details">
                  <h5>Height</h5>
                  <p><%= @record.height %></p>
                </div>
              </div> 
              <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-hand"></span>
                </div>
                <div class="contact-details">
                  <h5>Temperature</h5>
                  <p><%= @record.temperature %></p>
                </div>
              </div> 
              <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-database"></span>
                </div>
                <div class="contact-details">
                  <h5>Blood Presure</h5>
                  <p><%= @record.blood_pressure %></p>
                </div>
              </div>
              <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-user"></span>
                </div>
                <div class="contact-details">
                  <h5>Nurse</h5>
                  <p><%= @record.nurse_name %></p>
                </div>
              </div> 
            </div>

          <div class="col-lg-4 d-flex flex-column address-wrap"> 
            <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-bug"></span>
                </div>
                <div class="contact-details">
                  <h5>Complaint</h5>
                  <p><%= @record.complaints %></p>
                </div>
              </div> 
              <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-funnel"></span>
                </div>
                <div class="contact-details">
                  <h5>Diagnosis</h5>
                  <p><%= @record.icd.title %></p>
                </div>
              </div> 
              <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-magic-wand"></span>
                </div>
                <div class="contact-details">
                  <h5>Treatment</h5>
                  <p><%= @record.treatment %></p>
                </div>
              </div> 
              <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-user"></span>
                </div>
                <div class="contact-details">
                  <h5>Doctor</h5>
                  <p><%= @record.doctor_name %></p>
                </div>
              </div> 
              <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-pointer-right"></span>
                </div>
                <div class="contact-details">
                  <h5>Drugs Given</h5>
                  <p><%= @record.drugs_given %></p>
                </div>
              </div> 
              <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-user"></span>
                </div>
                <div class="contact-details">
                  <h5>Pharmacist</h5>
                  <p><%= @record.pharmacist_name %></p>
                </div>
              </div> 
            </div>
            <div class="col-lg-12 text-center">
              <%= link_to 'Edit', edit_record_path(@record), :class => "genric-btn info" %>  <%= link_to 'All Patients', records_path ,:class => "genric-btn info-border"%>                     
            </div>
          </div>
        </div>  
      </section>
      <!-- End contact-page Area -->