config/routes.rb
Rails.application.routes.draw do
  resources :personnels
  root to: 'home#index'
  resources :appointments
  resources :diseases
  resources :departments
  resources :records
  resources :nurses
  resources :doctors
  resources :pharmacists
  devise_for :users
  resources :frontdesk
  resources :home, only: [:index] do 
    collection do
      get :admin #, :personnels,:download_data, :new_personnel 
    end

    # member do
    #   get :show_personnel, :edit_personnel
    #   post :update_personnel
    # end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/pharmacists_controller.rb
class PharmacistsController < ApplicationController
  before_action :authenticate_user!
	before_action :set_record, only: [:show, :edit, :update, :destroy]

  def index
  	@records = Record.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).where(doctor_updated: true)
  end

  def new
  	@record = Record.new
  end

  def show
  end

  def edit
  end

  private
	# Use callbacks to share common setup or constraints between actions.
	def set_record
	  @record = Record.find(params[:id])
	end
end

app/views/pharmacists/_form.html.erb
<!-- Start contact-page Area -->
      <section class="contact-page-area section-gap">
        <div class="container">
          <div class="row">
            <div class="col-lg-4 d-flex flex-column address-wrap">
              <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-user"></span>
                </div>
                <div class="contact-details">
                  <h5>Name</h5>
                  <p>
                    <%=record.name %>
                  </p>
                </div>
              </div>
              <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-mustache"></span>
                </div>
                <div class="contact-details">
                  <h5>Date Of Birth</h5>
                  <p><%=record.dob %></p>
                </div>
              </div>
              <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-user"></span>
                </div>
                <div class="contact-details">
                  <h5>Gender</h5>
                  <p><%=record.gender %></p>
                </div>
              </div>   
              <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-map-marker"></span>
                </div>
                <div class="contact-details">
                  <h5>Address</h5>
                  <p><%=record.address %></p>
                </div>
              </div>  
              <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-apartment"></span>
                </div>
                <div class="contact-details">
                  <h5>Health Care Provider</h5>
                  <p><%=record.health_care_provider %></p>
                </div>
              </div> 
              <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-license"></span>
                </div>
                <div class="contact-details">
                  <h5>Department</h5>
                  <p><%= record.department.name %></p>
                </div>
              </div> 
                <div class="single-contact-address d-flex flex-row">
                  <div class="icon">
                    <span class="lnr lnr-pointer-down"></span>
                  </div>
                  <div class="contact-details">
                    <h5>Weight</h5>
                    <p><%= @record.weight %></p>
                  </div>
                </div> 
                <div class="single-contact-address d-flex flex-row">
                  <div class="icon">
                    <span class="lnr lnr-pointer-up"></span>
                  </div>
                  <div class="contact-details">
                    <h5>Height</h5>
                    <p><%= @record.height %></p>
                  </div>
                </div> 
                <div class="single-contact-address d-flex flex-row">
                  <div class="icon">
                    <span class="lnr lnr-hand"></span>
                  </div>
                  <div class="contact-details">
                    <h5>Temperature</h5>
                    <p><%= @record.temperature %></p>
                  </div>
                </div> 
                <div class="single-contact-address d-flex flex-row">
                  <div class="icon">
                    <span class="lnr lnr-database"></span>
                  </div>
                  <div class="contact-details">
                    <h5>Blood Presure</h5>
                    <p><%= @record.blood_pressure %></p>
                  </div>
                </div>                                                  
            </div>
            <div class="col-lg-8">
              <div class="row">
                <div class="col-lg-12 d-flex flex-column address-wrap">
                      <div class="single-contact-address d-flex flex-row">
                        <div class="icon">
                          <span class="lnr lnr-bug"></span>
                        </div>
                        <div class="contact-details">
                          <h5>Complaint</h5>
                          <p><%= @record.complaints %></p>
                        </div>
                      </div> 
                      <div class="single-contact-address d-flex flex-row">
                        <div class="icon">
                          <span class="lnr lnr-funnel"></span>
                        </div>
                        <div class="contact-details">
                          <h5>Diagnosis</h5>
                          <p><%= @record.icd.title %></p>
                        </div>
                      </div> 
                      <div class="single-contact-address d-flex flex-row">
                        <div class="icon">
                          <span class="lnr lnr-magic-wand"></span>
                        </div>
                        <div class="contact-details">
                          <h5>Treatment</h5>
                          <p><%= @record.treatment %></p>
                        </div>
                      </div> 
                    </div> 
              </div>
              <%= form_for(record, :html => {:class => "form-area contact-form text-right"}) do |f| %>
                <% if record.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(record.errors.count, "error") %> prohibited this record from being saved:</h2>

                    <ul>
                    <% record.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %> 
                <div class="row"> 
                  <div class="col-lg-6 form-group">
                  <%= f.text_field :drugs_given , class: "common-input mb-20 form-control", placeholder: "Drugs given" %>
                  <div class="col-lg-12">
                    <%= f.button "Update Record" ,:class=>"genric-btn primary", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Updating Record..."}%>                
                  </div>
                </div>
              <% end %>
                  </div>
                </div>
            </div>
          </div>
        </div>  
      </section>
      <!-- End contact-page Area -->

app/views/pharmacists/edit.html.erb
      <!-- start banner Area -->
      <section class="banner-area relative about-banner" id="home"> 
        <div class="overlay overlay-bg"></div>
        <div class="container">       
          <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content col-lg-12">
              <h1 class="text-white">
                Update Patient Record        
              </h1> 
              <p class="text-white link-nav"><a href="index.html">Home </a>  <span class="fa fa-arrow-right"></span> Update Record</p>
            </div>  
          </div>
        </div>
      </section>
      <!-- End banner Area --> 

<%= render 'form', record: @record %>

app/views/pharmacists/index.html.erb
      <!-- start banner Area -->
      <section class="banner-area relative about-banner" id="home"> 
        <div class="overlay overlay-bg"></div>
        <div class="container">       
          <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content col-lg-12">
              <h1 class="text-white">
                Pharmacist        
              </h1> 
              <p class="text-white link-nav"><a href="index.html">Home </a>  <span class="lnr lnr-arrow-right"></span>  Records</p>
            </div>  
          </div>
        </div>
      </section>
      <!-- End banner Area -->  

<% count = 0 %>

<% if @records.count > 0 %>
  <div class="limiter table-responsive">
    <div class="container-table100">
      <div class="wrap-table100">
        <p id="notice"><%= notice %></p>
        <div class="table100">
          <table>
            <thead>
              <tr>
                <th>S/No</th>
                <th>Name</th>
                <th>Age</th>
                <th>Gender</th>
                <th>Department</th>
                <th>Complaints</th>
                <th>Diagnosis</th>
                <th>Treatment</th>
                <th>Height</th>
                <th>Weight</th>
                <th>Temperature</th>
                <th>Blood pressure</th>
                <th>Drugs given</th>
                <th>Pharmacist name</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @records.each do |record| %>
                <% count+=1 %>
                <tr>
                  <td><%= count %></td>
                  <td><%= record.name %></td>
                  <td><%= record.age %></td>
                  <td><%= record.gender %></td>
                  <td><%= record.department.name %></td>
                  <td><%= record.complaints %></td>
                  <td><%= record.icd.title %></td>
                  <td><%= record.treatment %></td>
                  <td><%= record.height %></td>
                  <td><%= record.weight %></td>
                  <td><%= record.temperature %></td>
                  <td><%= record.blood_pressure %></td>
                  <td><%= record.drugs_given %></td>
                  <td><%= record.pharmacist_name %></td>  
                  <td><%= link_to 'Show', record %></td>             
                  <td><%= link_to 'Update Patient Record', edit_pharmacist_path(record) %></td>                  
                </tr>
              <% end %>
            </tbody>
          </table>

          </div>
      </div>
    </div>
  </div>

<br>
<% else %>
   <!-- Start facilities Area -->
      <section class="facilities-area section-gap">
        <div class="container">
                <div class="row d-flex justify-content-center">
                    <div class="menu-content pb-70 col-lg-7">
                        <div class="title text-center">
                          <p id="notice"><%= notice %></p>
                            <h1 class="mb-10">No Records.</h1>
                            <p>No patient record has been inputted for today. Click <%= link_to 'Refresh', records_path %> to start.</p>
                        </div>
                    </div>
                </div>
        </div>  
      </section>
      <!-- End facilities Area -->
<% end %>

app/views/pharmacists/new.html.erb
      <!-- start banner Area -->
      <section class="banner-area relative about-banner" id="home"> 
        <div class="overlay overlay-bg"></div>
        <div class="container">       
          <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content col-lg-12">
              <h1 class="text-white">
                New Record        
              </h1> 
              <p class="text-white link-nav"><a href="index.html">Home </a>  <span class="lnr lnr-arrow-right"></span>  <a href="contact.html">New Record</a></p>
            </div>  
          </div>
        </div>
      </section>
      <!-- End banner Area --> 

<%= render 'form', record: @record %>

<%= link_to 'Back', records_path %>

app/views/pharmacists/show.html.erb
     <!-- Start contact-page Area -->
      <section class="contact-page-area section-gap">
        <div class="container">
          <div class="row"> 
              <div class="col-lg-12">
                 <p id="notice"><%= notice %></p>
              </div>         
            <div class="col-lg-4 d-flex flex-column address-wrap">
              <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-user"></span>
                </div>
                <div class="contact-details">
                  <h5>Name</h5>
                  <p>
                    <%= @record.name %>
                  </p>
                </div>
              </div>
              <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-mustache"></span>
                </div>
                <div class="contact-details">
                  <h5>Age</h5>
                  <p><%= @record.age %></p>
                </div>
              </div>
              <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-map-marker"></span>
                </div>
                <div class="contact-details">
                  <h5>Address</h5>
                  <p><%= @record.address %></p>
                </div>
              </div> 
              <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-apartment"></span>
                </div>
                <div class="contact-details">
                  <h5>Health Care Provider</h5>
                  <p><%= @record.health_care_provider %></p>
                </div>
              </div> 
              <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-license"></span>
                </div>
                <div class="contact-details">
                  <h5>Address</h5>
                  <p><%= @record.department.name %></p>
                </div>
              </div> 
              <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-user"></span>
                </div>
                <div class="contact-details">
                  <h5>Front Desk Personnel</h5>
                  <p><%= @record.front_desk_name %></p>
                </div>
              </div>  
            </div>

            <div class="col-lg-4 d-flex flex-column address-wrap"> 
            <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-pointer-down"></span>
                </div>
                <div class="contact-details">
                  <h5>Weight</h5>
                  <p><%= @record.weight %></p>
                </div>
              </div> 
              <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-pointer-up"></span>
                </div>
                <div class="contact-details">
                  <h5>Height</h5>
                  <p><%= @record.height %></p>
                </div>
              </div> 
              <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-hand"></span>
                </div>
                <div class="contact-details">
                  <h5>Temperature</h5>
                  <p><%= @record.temperature %></p>
                </div>
              </div> 
              <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-database"></span>
                </div>
                <div class="contact-details">
                  <h5>Blood Presure</h5>
                  <p><%= @record.blood_pressure %></p>
                </div>
              </div>
            </div>

          <div class="col-lg-4 d-flex flex-column address-wrap"> 
            <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-bug"></span>
                </div>
                <div class="contact-details">
                  <h5>Complaint</h5>
                  <p><%= @record.complaints %></p>
                </div>
              </div> 
              <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-funnel"></span>
                </div>
                <div class="contact-details">
                  <h5>Diagnosis</h5>
                  <p><%= @record.icd.title %></p>
                </div>
              </div> 
              <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-magic-wand"></span>
                </div>
                <div class="contact-details">
                  <h5>Treatment</h5>
                  <p><%= @record.treatment %></p>
                </div>
              </div> 
              <div class="single-contact-address d-flex flex-row">
                <div class="icon">
                  <span class="lnr lnr-pointer-right"></span>
                </div>
                <div class="contact-details">
                  <h5>Drugs Given</h5>
                  <p><%= @record.drugs_given %></p>
                </div>
              </div> 
            </div>
            <div class="col-lg-12 text-center">
              <%= link_to 'Edit', edit_pharmacist_path(@record), :class => "genric-btn info" %>  <%= link_to 'All Patients', pharmacists_path ,:class => "genric-btn info-border"%>                     
            </div>
          </div>
        </div>  
      </section>
      <!-- End contact-page Area -->